# Generated by Django 3.2.9 on 2021-11-25 10:30

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0006_auto_20211125_1317'),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('r_first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('r_last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('r_middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('d_first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('d_last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('d_middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Фото')),
                ('passport_serial', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_issuing', models.CharField(max_length=250, verbose_name='Кем выдан')),
                ('passport_date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issuing_office_number', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('marital_status', models.CharField(blank=True, choices=[('Не женат/Не замужем', 'Не женат/Не замужем'), ('Женат/Замужем', 'Женат/Замужем'), ('Вдовец/вдова', 'Вдовец/вдова'), ('Разведен/Разведена', 'Разведен/Разведена')], max_length=25, null=True, verbose_name='Семейное положение')),
                ('adopted_date', models.DateField(auto_now_add=True, verbose_name='Принят')),
                ('dismissed_date', models.DateField(blank=True, verbose_name='Дата увольнения')),
                ('experience_before', models.IntegerField(verbose_name='Предыдущий стаж')),
                ('digital_work_book', models.BooleanField(default=False, verbose_name='"Электронная')),
                ('paper_work_book', models.BooleanField(default=False, verbose_name='Бумажная')),
                ('paper_work_book_image', models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Скан бумажной трудовой')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_card', to='mainapp.employee', verbose_name='Сотрудник')),
                ('main_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_main_address', to='guide.address', verbose_name='Адрес постоянной регистрации')),
                ('place_of_stay_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_place_of_stay_address', to='guide.address', verbose_name='Адрес временной регистрации')),
            ],
            options={
                'verbose_name': 'Карточка сотрудника',
                'verbose_name_plural': 'Карточки сотрудников',
            },
        ),
    ]
