# Generated by Django 3.2.9 on 2021-11-26 07:20

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150, verbose_name='Область/Край')),
                ('district', models.CharField(blank=True, max_length=150, verbose_name='Район')),
                ('city', models.CharField(max_length=150, verbose_name='Населенный пункт')),
                ('neighborhood', models.CharField(blank=True, max_length=150, verbose_name='Микрорайон')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('building', models.CharField(max_length=4, verbose_name='Дом/Строение')),
                ('apartment', models.CharField(blank=True, max_length=3, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('article_of_law', models.CharField(blank=True, max_length=250, verbose_name='Статья ТК')),
            ],
            options={
                'verbose_name': 'Причина увольнения',
                'verbose_name_plural': 'Причины увольнения',
            },
        ),
        migrations.CreateModel(
            name='WorkContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization', verbose_name='Организация')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Трудовой договор',
                'verbose_name_plural': 'Трудовые договоры',
            },
        ),
        migrations.CreateModel(
            name='OrderForEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('scan_file', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан приказа')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Приказ о приеме на работу',
                'verbose_name_plural': 'Приказы о приеме на работу',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_first_name', models.CharField(max_length=150, verbose_name='Имя "Кого?"')),
                ('r_last_name', models.CharField(max_length=150, verbose_name='Фамилия "Кого?"')),
                ('r_middle_name', models.CharField(max_length=150, verbose_name='Отчество "Кого?"')),
                ('d_first_name', models.CharField(max_length=150, verbose_name='Имя "Кому?"')),
                ('d_last_name', models.CharField(max_length=150, verbose_name='Фамилия "Кому?"')),
                ('d_middle_name', models.CharField(max_length=150, verbose_name='Отчество "Кому?"')),
                ('image', models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Фото')),
                ('passport_serial', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_issuing', models.CharField(max_length=250, verbose_name='Кем выдан')),
                ('passport_date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issuing_office_number', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('sex', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('marital_status', models.CharField(blank=True, choices=[('Не женат/Не замужем', 'Не женат/Не замужем'), ('Женат/Замужем', 'Женат/Замужем'), ('Вдовец/вдова', 'Вдовец/вдова'), ('Разведен/Разведена', 'Разведен/Разведена')], max_length=25, null=True, verbose_name='Семейное положение')),
                ('adopted_date', models.DateField(auto_now_add=True, verbose_name='Принят')),
                ('dismissed_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('experience_before', models.IntegerField(verbose_name='Предыдущий стаж')),
                ('digital_work_book', models.BooleanField(default=False, verbose_name='"Электронная')),
                ('paper_work_book', models.BooleanField(default=False, verbose_name='Бумажная')),
                ('paper_work_book_image', models.FileField(blank=True, upload_to=utils.uploading.file_upload_function, verbose_name='Скан бумажной трудовой')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_card', to='mainapp.employee', verbose_name='Сотрудник')),
                ('main_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_main_address', to='kadr.employeeaddress', verbose_name='Адрес постоянной регистрации')),
                ('place_of_stay_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_place_of_stay_address', to='kadr.employeeaddress', verbose_name='Адрес временной регистрации')),
            ],
            options={
                'verbose_name': 'Карточка сотрудника',
                'verbose_name_plural': 'Карточки сотрудников',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='На должность')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Заявление на работу',
                'verbose_name_plural': 'Заявления на работу',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.reason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
            },
        ),
    ]
