# Generated by Django 3.2.9 on 2021-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='i_middle_name',
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='d_first_name',
            field=models.CharField(max_length=150, verbose_name='Имя "Кому?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='d_last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия "Кому?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='d_middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество "Кому?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='r_first_name',
            field=models.CharField(max_length=150, verbose_name='Имя "Кого?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='r_last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия "Кого?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='r_middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество "Кого?"'),
        ),
    ]
