# Generated by Django 3.2.9 on 2022-07-22 14:13

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_employee_salary'),
        ('guide', '0002_label'),
        ('kadr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationforemployment',
            options={'verbose_name': 'Заявление на прием на работу', 'verbose_name_plural': 'Заявления на прием на работу'},
        ),
        migrations.AlterModelOptions(
            name='applicationfortransfer',
            options={'verbose_name': 'Заявление на перевод', 'verbose_name_plural': 'Заявления на перевод'},
        ),
        migrations.AddField(
            model_name='employeecard',
            name='appliccaton_for_employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.applicationforemployment', verbose_name='Заявление о приеме на работу'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='appliccaton_for_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.applicationfortransfer', verbose_name='Заявление о приеме на работу'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='bib_experience_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущий стаж библиотечный'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='branch_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.branchoffice', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Несовершеннолетние дети'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='covid_certificate',
            field=models.FileField(blank=True, upload_to='', verbose_name='Сертификат вакцинированного'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='order_for_employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.orderforemployment', verbose_name='Приказ о приеме на работу'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='work_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.workcontract', verbose_name='Трудовой договор'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='adopted_date',
            field=models.DateField(blank=True, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='digital_work_book',
            field=models.BooleanField(blank=True, default=False, verbose_name='"Электронная'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='experience_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущий стаж полный'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='main_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_main_address', to='kadr.employeeaddress', verbose_name='Адрес постоянной регистрации'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='paper_work_book',
            field=models.BooleanField(blank=True, default=False, verbose_name='Бумажная'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='place_of_stay_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_place_of_stay_address', to='kadr.employeeaddress', verbose_name='Фактический адрес проживания'),
        ),
        migrations.CreateModel(
            name='PersonalDataAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('agreement_file', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadr.employeecard', verbose_name='Соглашение о персоналных данных')),
            ],
            options={
                'verbose_name': 'Соглашение об обработке персоналных данных',
                'verbose_name_plural': 'Соглашения об обработке персональных данных',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Нименование')),
                ('color', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='guide.label', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статусы сотрудников',
            },
        ),
        migrations.CreateModel(
            name='CovidCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('certificate_file', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadr.employeecard', verbose_name='Сертифика о вакцинации')),
            ],
            options={
                'verbose_name': 'Сертификат о вакцинации',
                'verbose_name_plural': 'Сертификаты вакцинированных',
            },
        ),
        migrations.AddField(
            model_name='employeecard',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.employeestatus', verbose_name='Рабочий статус'),
        ),
    ]
