# Generated by Django 3.2.9 on 2021-11-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_employee_options'),
        ('kadr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='branch_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.branchoffice', verbose_name='Филиал'),
        ),
    ]
