# Generated by Django 3.2.9 on 2021-11-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0002_auto_20211125_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150, verbose_name='Область/Край')),
                ('district', models.CharField(blank=True, max_length=150, verbose_name='Район')),
                ('city', models.CharField(max_length=150, verbose_name='Населенный пункт')),
                ('neighborhood', models.CharField(blank=True, max_length=150, verbose_name='Микрорайон')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('building', models.CharField(max_length=4, verbose_name='Дом/Строение')),
                ('apartment', models.CharField(blank=True, max_length=3, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='main_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_main_address', to='kadr.employeeaddress', verbose_name='Адрес постоянной регистрации'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='place_of_stay_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_place_of_stay_address', to='kadr.employeeaddress', verbose_name='Адрес временной регистрации'),
        ),
    ]
