# Generated by Django 3.2.9 on 2022-07-23 10:14

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_employee_salary'),
        ('kadr', '0002_auto_20220722_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('file', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Файл инструкций')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization', verbose_name='Организация')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должностная инструкция',
                'verbose_name_plural': 'Должностные инструкции',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForPositionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан заявления')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.reason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Заявление на перевод',
                'verbose_name_plural': 'Заявления на перевод',
            },
        ),
        migrations.AddField(
            model_name='employeecard',
            name='position_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.positioninstruction', verbose_name='Должностные инструкции'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='appliccaton_for_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.applicationforpositiontransfer', verbose_name='Заявление о приеме на работу'),
        ),
    ]
