# Generated by Django 3.2.9 on 2021-12-02 06:31

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0003_auto_20211130_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='appliccaton_for_employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.applicationforemployment', verbose_name='Заявление о приеме на работу'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='order_for_employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.orderforemployment', verbose_name='Приказ о приеме на работу'),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='work_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.workcontract', verbose_name='Трудовой договор'),
        ),
        migrations.CreateModel(
            name='PersonalDataAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('agreement_file', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadr.employeecard', verbose_name='Соглашение о персоналных данных')),
            ],
            options={
                'verbose_name': 'Соглашение об обработке персоналных данных',
                'verbose_name_plural': 'Соглашения об обработке персональных данных',
            },
        ),
        migrations.CreateModel(
            name='CovidCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('certificate_file', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadr.employeecard', verbose_name='Сертифика о вакцинации')),
            ],
            options={
                'verbose_name': 'Сертификат о вакцинации',
                'verbose_name_plural': 'Сертификаты вакцинированных',
            },
        ),
        migrations.AddField(
            model_name='employeecard',
            name='covid_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kadr.covidcertificate', verbose_name='Сертификат вакцинированного'),
        ),
    ]
