# Generated by Django 3.2.9 on 2021-11-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0003_auto_20211125_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='dismissed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
    ]
