# Generated by Django 4.0.3 on 2022-04-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0004_auto_20211203_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='bib_experience_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущий стаж библиотечный'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='experience_before',
            field=models.IntegerField(verbose_name='Предыдущий стаж полный'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='place_of_stay_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_place_of_stay_address', to='kadr.employeeaddress', verbose_name='Фактический адрес проживания'),
        ),
    ]
