# Generated by Django 3.2.9 on 2021-12-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0004_auto_20211202_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationforemployment',
            options={'verbose_name': 'Заявление на прием на работу', 'verbose_name_plural': 'Заявления на прием на работу'},
        ),
        migrations.AlterModelOptions(
            name='applicationfortransfer',
            options={'verbose_name': 'Заявление на перевод', 'verbose_name_plural': 'Заявления на перевод'},
        ),
    ]
