# Generated by Django 3.2.9 on 2021-11-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0004_alter_employeecard_dismissed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='place_of_stay_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_place_of_stay_address', to='kadr.employeeaddress', verbose_name='Адрес временной регистрации'),
        ),
    ]
