# Generated by Django 4.0.3 on 2022-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0005_employeecard_bib_experience_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='bib_experience_before',
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='experience_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущий стаж полный'),
        ),
    ]
