# Generated by Django 3.2.9 on 2021-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0005_auto_20211202_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='adopted_date',
            field=models.DateField(blank=True, verbose_name='Принят'),
        ),
    ]
