# Generated by Django 3.2.9 on 2021-11-25 13:20

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0005_alter_employeecard_place_of_stay_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='paper_work_book_image',
            field=models.ImageField(blank=True, upload_to=utils.uploading.file_upload_function, verbose_name='Скан бумажной трудовой'),
        ),
    ]
