# Generated by Django 4.0.3 on 2022-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0006_remove_employeecard_bib_experience_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='bib_experience_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущий стаж библиотечный'),
        ),
    ]
