# Generated by Django 3.2.9 on 2021-12-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0006_alter_employeecard_adopted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статусы сотрудников',
            },
        ),
    ]
