# Generated by Django 3.2.9 on 2022-07-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0006_auto_20220725_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='place_of_stay_address',
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='bib_experience_before',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Предыдущий стаж библиотечный'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='experience_before',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Предыдущий стаж полный'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='main_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_main_address', to='kadr.employeeaddress', verbose_name='Адрес регистрации'),
        ),
    ]
