# Generated by Django 3.2.9 on 2021-11-25 14:39

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211125_1317'),
        ('kadr', '0007_alter_employeecard_paper_work_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('article_of_law', models.CharField(blank=True, max_length=250, verbose_name='Статья ТК')),
            ],
            options={
                'verbose_name': 'Причина увольннения',
                'verbose_name_plural': 'Причины увольнения',
            },
        ),
        migrations.CreateModel(
            name='OrderForEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('scan_file', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан приказа')),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Приказ о приеме на работу',
                'verbose_name_plural': 'Приказы о приеме на работу',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='На должность')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Заявление на работу',
                'verbose_name_plural': 'Заявления на работу',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.reason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
            },
        ),
    ]
