# Generated by Django 4.0.3 on 2022-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0007_employeecard_bib_experience_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Несовершеннолетние дети'),
        ),
    ]
