# Generated by Django 3.2.9 on 2021-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0008_auto_20211202_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
    ]
