# Generated by Django 3.2.9 on 2021-12-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0009_employeestatus_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'verbose_name': 'Статус сотрудника', 'verbose_name_plural': 'Статусы сотрудников'},
        ),
    ]
