version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/web
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    depends_on:
      - web


