# Generated by Django 3.2.9 on 2021-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150, verbose_name='Область/Край')),
                ('district', models.CharField(blank=True, max_length=150, verbose_name='Район')),
                ('city', models.CharField(max_length=150, verbose_name='Населенный пункт')),
                ('neighborhood', models.CharField(blank=True, max_length=150, verbose_name='Микрорайон')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('building', models.CharField(max_length=4, verbose_name='Дом/Строение')),
                ('apartment', models.CharField(blank=True, max_length=3, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250, verbose_name='Наименование банка')),
                ('bic_number', models.CharField(max_length=9, verbose_name='БИК Банка')),
                ('correspondent_account', models.CharField(max_length=20, verbose_name='Кор. счет')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
    ]
