# Generated by Django 3.2.9 on 2021-11-26 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=250, verbose_name='Краткое наименование')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы/Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='mainapp.position', verbose_name='Подчиняется')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='OrganizationBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Рабочее название')),
                ('payment_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('account_currency', models.CharField(blank=True, choices=[('Рубль', 'Рубль'), ('Евро', 'Евро'), ('Доллар', 'Доллар')], default='Рубль', max_length=10, null=True, verbose_name='Валюта счета')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Банковский Счет',
                'verbose_name_plural': 'Банковские счета организации',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=250, verbose_name='Краткое наименование')),
                ('logo', models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Логотип')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(max_length=8, verbose_name='ОКПО')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('primary', models.BooleanField(default=False, verbose_name='Основная')),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organizationbankaccount', verbose_name='Баковские реквизиты')),
                ('fact_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_address', to='guide.address', verbose_name='Фактический адрес')),
                ('legal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_address', to='guide.address', verbose_name='Юридический адрес')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Есть whatsapp')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Оклад')),
                ('branch_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.branchoffice', verbose_name='Филиал')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Список Сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=18, verbose_name='Номер телефона')),
                ('employees', models.ManyToManyField(blank=True, related_name='employees', to='mainapp.Employee', verbose_name='Сотрудники')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='mainapp.employee', verbose_name='Руководитель')),
                ('parent_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.branchoffice', verbose_name='Входит в состав')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='departments',
            field=models.ManyToManyField(blank=True, to='mainapp.Department', verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.employee', verbose_name='Руководитель подразделения'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='mainapp.branchoffice', verbose_name='Подчиняется'),
        ),
    ]
