# Generated by Django 3.2.9 on 2021-11-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Рабочее название')),
                ('payment_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('account_currency', models.CharField(blank=True, choices=[('Рубль', 'Рубль'), ('Евро', 'Евро'), ('Доллар', 'Доллар')], default='Рубль', max_length=10, null=True, verbose_name='Валюта счета')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Банковский Счет',
                'verbose_name_plural': 'Банковские счета',
            },
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=250, verbose_name='Краткое наименование')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы/Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Есть whatsapp')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Оклад')),
                ('branch_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.branchoffice', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Список Сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='mainapp.position', verbose_name='Подчиняется')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=250, verbose_name='Краткое наименование')),
                ('logo', models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Логотип')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(max_length=8, verbose_name='ОКПО')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bankaccount', verbose_name='Баковские реквизиты')),
                ('fact_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_address', to='guide.address', verbose_name='Фактический адрес')),
                ('legal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_address', to='guide.address', verbose_name='Юридический адрес')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('r_first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('r_last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('r_middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('d_first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('d_last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('d_middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Фото')),
                ('passport_serial', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_issuing', models.CharField(max_length=250, verbose_name='Кем выдан')),
                ('passport_date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issuing_office_number', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('marital_status', models.CharField(blank=True, choices=[('Не женат/Не замужем', 'Не женат/Не замужем'), ('Женат/Замужем', 'Женат/Замужем'), ('Вдовец/вдова', 'Вдовец/вдова'), ('Разведен/Разведена', 'Разведен/Разведена')], max_length=25, null=True, verbose_name='Семейное положение')),
                ('adopted_date', models.DateField(auto_now_add=True, verbose_name='Принят')),
                ('dismissed_date', models.DateField(blank=True, verbose_name='Дата увольнения')),
                ('experience_before', models.IntegerField(verbose_name='Предыдущий стаж')),
                ('digital_work_book', models.BooleanField(default=False, verbose_name='"Электронная')),
                ('paper_work_book', models.BooleanField(default=False, verbose_name='Бумажная')),
                ('paper_work_book_image', models.ImageField(blank=True, upload_to=utils.uploading.file_upload_function, verbose_name='Скан бумажной трудовой')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee', verbose_name='Сотрудник')),
                ('main_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guide.address', verbose_name='Адрес постоянной регистрации')),
                ('place_of_stay_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_of_stay_address', to='guide.address', verbose_name='Адрес временной регистрации')),
            ],
            options={
                'verbose_name': 'Карточка сотрудника',
                'verbose_name_plural': 'Личные карточки сотрудников',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='mainapp.employeecard', verbose_name='Карточка сотрудника'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=18, verbose_name='Номер телефона')),
                ('employees', models.ManyToManyField(related_name='employees', to='mainapp.Employee', verbose_name='Сотрудники')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='mainapp.employee', verbose_name='Руководитель')),
                ('parent_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.branchoffice')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='departments',
            field=models.ManyToManyField(blank=True, to='mainapp.Department', verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.employee', verbose_name='Руководитель подразделения'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='mainapp.branchoffice', verbose_name='Подчиняется'),
        ),
    ]
