# Generated by Django 3.2.9 on 2021-11-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.employee', verbose_name='Руководитель подразделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employees', to='mainapp.Employee', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='mainapp.employee', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.branchoffice', verbose_name='Входит в '),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Оклад'),
        ),
    ]
