# Generated by Django 3.2.9 on 2022-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_organization_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeecard',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=18, verbose_name='Телефон'),
        ),
    ]
