# Generated by Django 3.2.9 on 2021-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211123_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='i_middle_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='d_first_name',
            field=models.CharField(max_length=150, verbose_name='Имя "Кому?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='d_last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия "Кому?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='d_middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество "Кому?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='r_first_name',
            field=models.CharField(max_length=150, verbose_name='Имя "Кого?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='r_last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия "Кого?"'),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='r_middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество "Кого?"'),
        ),
    ]
