# Generated by Django 3.2.9 on 2021-11-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
        ('mainapp', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch_office',
        ),
        migrations.AlterField(
            model_name='organization',
            name='fact_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fact_address', to='guide.address', verbose_name='Почтовый адрес'),
        ),
    ]
