# Generated by Django 3.2.9 on 2022-07-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_label'),
        ('mainapp', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Нименование')),
                ('color', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='guide.label', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статусы сотрудников',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.employeestatus', verbose_name='Рабочий статус'),
        ),
    ]
