# Generated by Django 3.2.9 on 2021-11-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
        ('mainapp', '0004_auto_20211123_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='OrganizationBankAccount',
        ),
    ]
