# Generated by Django 3.2.9 on 2021-11-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_bankaccount_organizationbankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationbankaccount',
            options={'verbose_name': 'Банковский Счет', 'verbose_name_plural': 'Банковские счета организации'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='card',
        ),
        migrations.DeleteModel(
            name='EmployeeCard',
        ),
    ]
