# Generated by Django 3.2.9 on 2021-11-26 07:20

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Приказ', 'Приказ'), ('Письмо', 'Письмо'), ('Требование', 'Требование')], default='Приказ', max_length=20)),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('scan_image', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа')),
                ('contragent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contragent', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Входящий документ',
                'verbose_name_plural': 'Входящие документы',
            },
        ),
        migrations.CreateModel(
            name='InternalOrderOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('scan_image', models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа')),
                ('base_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.incomingdocument', verbose_name='Основание')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Приказ по организации',
                'verbose_name_plural': 'Приказы по организации',
            },
        ),
    ]
