# Generated by Django 3.2.9 on 2021-11-25 13:32

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_applicationforemployment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationforemployment',
            options={'verbose_name': 'Заявление на работу', 'verbose_name_plural': 'Заявления на работу'},
        ),
        migrations.AlterField(
            model_name='incomingdocument',
            name='scan_image',
            field=models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа'),
        ),
        migrations.AlterField(
            model_name='internalorderorganization',
            name='scan_image',
            field=models.FileField(upload_to=utils.uploading.file_upload_function, verbose_name='Скан документа'),
        ),
    ]
