# Generated by Django 3.2.9 on 2021-11-25 13:54

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211125_1317'),
        ('documents', '0003_auto_20211125_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationforemployment',
            old_name='interval_number',
            new_name='internal_number',
        ),
        migrations.CreateModel(
            name='ApplicationForDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('application_scan', models.FileField(upload_to=utils.uploading.file_upload_function)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
            },
        ),
    ]
