# Generated by Django 3.2.9 on 2021-11-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20211125_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationforemployment',
            name='position',
        ),
        migrations.DeleteModel(
            name='ApplicationForDismissal',
        ),
        migrations.DeleteModel(
            name='ApplicationForEmployment',
        ),
    ]
