# Generated by Django 3.2.9 on 2021-11-25 09:41

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0005_rename_bankaccount_organizationbankaccount'),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContragentBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Рабочее название')),
                ('payment_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('account_currency', models.CharField(blank=True, choices=[('Рубль', 'Рубль'), ('Евро', 'Евро'), ('Доллар', 'Доллар')], default='Рубль', max_length=10, null=True, verbose_name='Валюта счета')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Банковский счет контрагента',
                'verbose_name_plural': 'Банковские счета контрагентов',
            },
        ),
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=150, verbose_name='Рабочее наименование')),
                ('logo', models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Логотип')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(max_length=8, verbose_name='ОКПО')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contragentbankaccount', verbose_name='Баковские реквизиты')),
                ('fact_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contragent_fact_address', to='guide.address', verbose_name='Фактический адрес')),
                ('legal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contragent_legal_address', to='guide.address', verbose_name='Юридический адрес')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название в списке')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Есть whatsapp')),
                ('viber', models.BooleanField(default=False, verbose_name='Есть viber')),
                ('telegram', models.BooleanField(default=False, verbose_name='Есть telegram')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contragent', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
