# Generated by Django 3.2.9 on 2021-11-25 13:20

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.uploading.image_upload_function, verbose_name='Фото'),
        ),
    ]
