# Generated by Django 3.2.9 on 2021-11-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contragent',
            name='ogrn',
        ),
        migrations.RemoveField(
            model_name='contragent',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='contragent',
            name='bank_details',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contragentbankaccount', verbose_name='Баковские реквизиты'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='okpo',
            field=models.CharField(blank=True, max_length=8, verbose_name='ОКПО'),
        ),
    ]
