# Generated by Django 3.2.9 on 2021-11-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
        ('crm', '0003_auto_20211125_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='fact_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contragent_fact_address', to='guide.address', verbose_name='Почтовый адрес'),
        ),
    ]
